language: node_js
node_js:
  - "9.11.2"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - TRAVIS=travis CXX=g++-4.8 MONGO_URI=127.0.0.1:27017
services:
  - mongodb
